#                   ANN model Building

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [3]:
dataset.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = dataset.iloc[:, 3:13].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
y = dataset.iloc[:, 13].values
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

# Encoding categorical data…

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]
X

C:\Users\PABITRA\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\PABITRA\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

# Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
X_train.shape

(8000, 11)

# Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Importing the Keras libraries and packages

In [9]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


# Initializing the ANN…

In [10]:
classifier = Sequential()

# Adding the input layer and the first hidden layer…

In [11]:
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))

Instructions for updating:
Colocations handled automatically by placer.


C:\Users\PABITRA\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


# Adding the second hidden layer…

In [12]:
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

C:\Users\PABITRA\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


# Adding the output layer…

In [13]:
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

C:\Users\PABITRA\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


# Compiling the ANN…

In [14]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set

In [15]:
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

Instructions for updating:
Use tf.cast instead.


C:\Users\PABITRA\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/100
8000/8000 [==============================] - 2s 245us/step - loss: 0.4836 - acc: 0.7955
Epoch 2/100
8000/8000 [==============================] - 1s 177us/step - loss: 0.4272 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.4213 - acc: 0.8017
Epoch 4/100
8000/8000 [==============================] - 1s 171us/step - loss: 0.4175 - acc: 0.8239
Epoch 5/100
8000/8000 [==============================] - 1s 181us/step - loss: 0.4155 - acc: 0.8282
Epoch 6/100
8000/8000 [==============================] - 1s 186us/step - loss: 0.4138 - acc: 0.8306
Epoch 7/100
8000/8000 [==============================] - 1s 180us/step - loss: 0.4126 - acc: 0.8316
Epoch 8/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.4111 - acc: 0.8327
Epoch 9/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.4101 - acc: 0.8334
Epoch 10/100
8000/8000 [==============================] - 1s 183us/step - loss: 0.4093 - acc: 0.8340

8000/8000 [==============================] - 1s 173us/step - loss: 0.4006 - acc: 0.8354
Epoch 83/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.4010 - acc: 0.8349
Epoch 84/100
8000/8000 [==============================] - 1s 173us/step - loss: 0.4011 - acc: 0.8359
Epoch 85/100
8000/8000 [==============================] - 1s 176us/step - loss: 0.4010 - acc: 0.8359
Epoch 86/100
8000/8000 [==============================] - 1s 150us/step - loss: 0.4010 - acc: 0.8365
Epoch 87/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.4008 - acc: 0.8342
Epoch 88/100
8000/8000 [==============================] - 1s 168us/step - loss: 0.4011 - acc: 0.8341
Epoch 89/100
8000/8000 [==============================] - 1s 146us/step - loss: 0.4008 - acc: 0.8341
Epoch 90/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.4005 - acc: 0.8352
Epoch 91/100
8000/8000 [==============================] - 1s 179us/step - loss: 0.4002 - acc: 0.8357
Epo

# Making the predictions and evaluating the model

In [16]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred 

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

# Making the Confusion Matrix

In [17]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1541,   54],
       [ 257,  148]], dtype=int64)

In [18]:
from sklearn.metrics import precision_recall_fscore_support,classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

       False       0.97      0.86      0.91      1798
        True       0.37      0.73      0.49       202

    accuracy                           0.84      2000
   macro avg       0.67      0.79      0.70      2000
weighted avg       0.91      0.84      0.87      2000



In [19]:
False

False